### ISSUE TITLE
PSP public announcement checklist

### ISSUE THREAD

**Issue by Beyley** [LittleBigRefresh/Refresh#176]
# Overview
This issue details the tasks needed to be completed before we will publicly announce and officially release PSP support.
Tasks are in no particular order, and this is not an exhaustive list. Specific tasks can be brought out to separate issues if they need extra discussion/clarification.

Once all tasks are complete, that does not necessarily mean PSP support is ready for announcement, we will make another assessment at that time to determine if we are ready. (And vice versa, not all tasks need to be done for PSP to be considered ready for announcement)

There is no ETA, please do not ask.

# Unimplemented search queries
 - [x] #185 
 - [x] #186
 - [x] #181
 - [x] #182

# Slots
 - [x] #180 
 - [x] #178
 - [x] Developer leaderboards

# Rate limiting
 - [x] #183

# Users
- [x] #184 
- [x] Hearted creators seems inconsistent, see [this report](https://discord.com/channels/1049223665243389953/1049223665998372947/1157145476139864104)
- [x] Hearted levels also seems inconsistent, see [here](https://discord.com/channels/1049223665243389953/1049223665998372947/1157145476139864104)

# News
- [x] #179 

# Grief reports
- [x] #187

# Do-gooders
- [ ] Patch EULA to AGPL license (see Allefresher)

**Comment by jvyden** [comment]
Highest Rated and Most Hearted should just be a trivial implementation - we already support these so they just need to be aliased.

**Comment by jvyden** [comment]
I find everything easier to manage with individual issues so I converted everything to them. I don't mind meta issues, though, so I'll keep this open.

**Comment by Beyley** [comment]
> Highest Rated and Most Hearted should just be a trivial implementation - we already support these so they just need to be aliased.

I have #177 which adds aliasing support and aliases/tests highest rated, and most hearted will come in a later PR, although CI seems to be failing for unknown reasons

**Comment by jvyden** [comment]
We've released an announcement regarding PSP publically, so closing for now.
