### ISSUE TITLE
User content metadata tracking

### ISSUE THREAD

**Issue by jvyden** [LittleBigRefresh/Refresh#24]
- [x] Track who uploaded an asset, and when
- [x] Track type of asset (https://github.com/LittleBigRefresh/Refresh/issues/22)
- [ ] Track dependencies of asset
- [x] Add migration to backfill data into database from DataStore
- [ ] Track size of asset (https://github.com/LittleBigRefresh/Refresh/issues/66)

We can use this information to be able to purge unused assets/delete assets by a certain user

**Comment by jvyden** [comment]
Working on this [in this branch](https://github.com/jvyden/Refresh/tree/assets)

**Comment by jvyden** [comment]
Mostly complete now and merged into main, all that's left is dependency tracking.
